apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Référence au base (si vous en avez un)
# resources:
#   - ../../../base/zabbix

# Pour l'instant on laisse vide ou on référence seulement le namespace si besoin