apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zabbix-ingress
  namespace: zabbix
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: zabbix.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nova-zabbix-zabbix-web
                port:
                  number: 80