# Configuration par défaut pour Zabbix (base)
zabbix-server:
  enabled: true
  resources:
    requests:
      cpu: 300m
      memory: 512Mi

zabbix-web:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - zabbix.nova-syndicate.local

zabbix-proxy:
  enabled: false

postgresql:
  enabled: true
  persistence:
    storageClass: "longhorn"
    size: 1Gi

persistence:
  enabled: true
  storageClass: "longhorn"
  size: 1Gi