zabbix-server:
  enabled: true
  nodeSelector:
    kubernetes.io/hostname: zabbix-monitoring
  resources:
    requests:
      cpu: 300m
      memory: 512Mi

zabbix-web:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - zabbix.nova-syndicate.local

zabbix-proxy:
  enabled: true

persistence:
  enabled: true
  storageClass: "longhorn"
  size: 5Gi

postgresql:
  enabled: true
  persistence:
    storageClass: "longhorn"
    size: 5Gi