apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml  # À créer
helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 87.2.1  # Version stable
    releaseName: prometheus
    namespace: monitoring
    valuesFile: values.yaml