apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nova-syndicate
resources:
  - ../../base/namespace
  # - ../../base/deployments  # À décommenter plus tard
  # - ../../base/services     # À décommenter plus tard