apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 7.7.0
    helm:
      values: |
        global:
          nodeSelector:
            kubernetes.io/hostname: k3s-lyon-01

        # === Tolerations pour tous les composants ===
        tolerations:
          - key: dedicated
            operator: Equal
            value: monitoring
            effect: NoSchedule
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: NoSchedule

        controller:
          tolerations: []

        server:
          tolerations: []
          extraArgs:
            - --insecure
          service:
            type: ClusterIP

        repoServer:
          tolerations: []

        dex:
          tolerations: []

        redis:
          tolerations: []

        notifications:
          tolerations: []

        applicationSet:
          tolerations: []

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true