# manifests/overlays/lab/postgresql/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-ha
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql-ha
    targetRevision: "13.*"    # ArgoCD prend la plus récente 13.x
    helm:
      releaseName: postgresql-ha
      valuesObject:
        postgresql:
          replicaCount: 3
          resources:
            requests:
              cpu: 250m
              memory: 1Gi
            limits:
              cpu: 500m
              memory: 2Gi
          persistence:
            enabled: true
            storageClass: longhorn
            size: 8Gi
        patroni:
          scope: nova-lab
          postgresql:
            parameters:
              max_connections: 100
              shared_buffers: 128MB
              wal_buffers: 8MB
              synchronous_commit: remote_write
              synchronous_standby_names: '1'
          nodeSelector:
            kubernetes.io/hostname: k3s-lyon-01
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      app.kubernetes.io/name: postgresql-ha
                  topologyKey: kubernetes.io/hostname
  destination:
    server: https://kubernetes.default.svc
    namespace: nova-syndicate
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
