apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 88.5.2
    chart: kube-prometheus-stack
    helm:
      releaseName: prometheus
      values: |
        # Configuration pour Prometheus
        prometheus:
          prometheusSpec:
            replicas: 1
            retention: 2d
            retentionSize: 1Gi
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: longhorn
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 2Gi
            nodeSelector:
              kubernetes.io/hostname: k3s-worker-mrs  # Changé ici

        # Configuration pour Grafana
        grafana:
          persistence:
            enabled: true
            storageClassName: longhorn
            size: 1Gi
          adminPassword: "admin123456"
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - grafana.local
          datasources:
            datasources.yaml:
              apiVersion: 1
              datasources:
                - name: Prometheus
                  type: prometheus
                  url: http://prometheus-kube-prometheus-prometheus.monitoring:9090
                  access: proxy
          nodeSelector:  # Ajouté ici pour Grafana
            kubernetes.io/hostname: k3s-worker-mrs

        # Désactive AlertManager (optionnel)
        alertmanager:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
