apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nova-zabbix
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://zabbix.github.io/helm-charts
    chart: zabbix
    targetRevision: "2.6.0"   # Version stable récente
    helm:
      valueFiles:
        - values-zabbix.yaml
      releaseName: zabbix
  destination:
    server: https://kubernetes.default.svc
    namespace: zabbix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: ""
      kind: ConfigMap
      name: ".*"