apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nova-zabbix
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://zabbix-community.github.io/helm-charts   # Repo communautaire stable
    chart: zabbix
    targetRevision: "2.6.0"
    helm:
      valueFiles:
        - values-zabbix.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: zabbix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true