apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nova-zabbix
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://zabbix-community.github.io/helm-zabbix  # URL correcte
    targetRevision: 1.0.0
    chart: zabbix
    helm:
      values: |
        zabbix-server:
          enabled: true
          nodeSelector:
            kubernetes.io/hostname: zabbix-monitoring
          resources:
            requests:
              cpu: 300m
              memory: 512Mi
        zabbix-web:
          enabled: true
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - zabbix.nova-syndicate.local
        zabbix-proxy:
          enabled: true
        persistence:
          enabled: true
          storageClass: "longhorn"
          size: 5Gi
        postgresql:
          enabled: true
          persistence:
            storageClass: "longhorn"
            size: 5Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: zabbix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true