---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart disk-hygiene timer
  ansible.builtin.systemd:
    name: "{{ disk_hygiene_timer_name }}.timer"
    state: restarted
    enabled: true
  when: disk_hygiene_timer_enabled | bool

- name: Restart disk-watch timer
  ansible.builtin.systemd:
    name: disk-watch.timer
    state: restarted
    enabled: true
  when: disk_hygiene_watch_enabled | bool
