grafana:
  persistence:
    enabled: true
    storageClass: "longhorn"
    size: 1Gi
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.nova-syndicate.local
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
  nodeSelector: # Ajouté
    kubernetes.io/hostname: k3s-worker-mrs

prometheus:
  prometheusSpec:
    replicas: 1
    retention: 2d
    retentionSize: 1Gi
    nodeSelector: # Ajouté
      kubernetes.io/hostname: k3s-worker-mrs # j'ai changé ici pour spécifier le nœud où Prometheus doit être déployé sans taint
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi
    resources:
      requests:
        cpu: 400m
        memory: 1Gi

alertmanager:
  enabled: true
  alertmanagerSpec:
    nodeSelector: # Ajouté si alertmanager est activé
      kubernetes.io/hostname: k3s-worker-mrs
