apiVersion: v1
data:
  config.yaml: |-
    issuer: http://10.0.1.2:32000/dex
    storage:
      type: memory
    web:
      http: 0.0.0.0:5556
    connectors:
    - type: ldap
      id: ldap
      name: OpenLDAP Assurance
      config:
        host: openldap.identity.svc.cluster.local:389
        insecureNoSSL: true
        insecureSkipVerify: true
        bindDN: cn=admin,dc=assurance,dc=local
        bindPW: __VAULT_LDAP_BIND_PASSWORD__
        userSearch:
          baseDN: ou=users,dc=assurance,dc=local
          filter: "(objectClass=inetOrgPerson)"
          username: uid
          idAttr: uid
          emailAttr: uid
          nameAttr: cn
        groupSearch:
          baseDN: ou=groups,dc=assurance,dc=local
          filter: "(objectClass=groupOfNames)"
          userMatchers:
          - userAttr: DN
            groupAttr: member
          nameAttr: cn
    staticClients:
    - id: kubernetes
      redirectURIs:
      - http://127.0.0.1:8000
      - http://localhost:8000
      name: Kubernetes
      secret: kubernetes-secret-lab-2026
    oauth2:
      skipApprovalScreen: true
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: dex-config
  namespace: identity
