apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-data
  namespace: keycloak
  labels:
    app: keycloak
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn          # adaptez si votre StorageClass est différente
  resources:
    requests:
      storage: 1Gi
