apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"openldap","namespace":"identity"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"openldap"}},"template":{"metadata":{"labels":{"app":"openldap"}},"spec":{"containers":[{"env":[{"name":"LDAP_ORGANISATION","value":"Assurance Demo"},{"name":"LDAP_DOMAIN","value":"assurance.local"},{"name":"LDAP_ADMIN_PASSWORD","valueFrom":{"secretKeyRef":{"key":"LDAP_ADMIN_PASSWORD","name":"openldap-secret"}}},{"name":"LDAP_CONFIG_PASSWORD","valueFrom":{"secretKeyRef":{"key":"LDAP_CONFIG_PASSWORD","name":"openldap-secret"}}},{"name":"LDAP_TLS","value":"false"}],"image":"osixia/openldap:1.5.0","name":"openldap","ports":[{"containerPort":389,"name":"ldap"},{"containerPort":636,"name":"ldaps"}],"volumeMounts":[{"mountPath":"/var/lib/ldap","name":"data"},{"mountPath":"/etc/ldap/slapd.d","name":"config"}]}],"volumes":[{"name":"data","persistentVolumeClaim":{"claimName":"openldap-pvc"}},{"emptyDir":{},"name":"config"}]}}}}
  creationTimestamp: "2026-07-29T15:39:28Z"
  generation: 8
  name: openldap
  namespace: identity
  resourceVersion: "64059990"
  uid: 6429e0cc-f8df-48e2-8281-390e35078371
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: openldap
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-ldap-admin: secret/data/ldap/admin
        vault.hashicorp.com/agent-inject-template-ldap-admin: |-
          {{- with secret "secret/data/ldap/admin" -}}
          {{ .Data.data.password }}
          {{- end }}
        vault.hashicorp.com/role: ldap-admin
      creationTimestamp: null
      labels:
        app: openldap
    spec:
      containers:
      - env:
        - name: LDAP_ORGANISATION
          value: Assurance Demo
        - name: LDAP_DOMAIN
          value: assurance.local
        - name: LDAP_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: LDAP_ADMIN_PASSWORD
              name: openldap-secret
        - name: LDAP_CONFIG_PASSWORD
          valueFrom:
            secretKeyRef:
              key: LDAP_CONFIG_PASSWORD
              name: openldap-secret
        - name: LDAP_TLS
          value: "false"
        image: osixia/openldap:1.5.0
        imagePullPolicy: IfNotPresent
        name: openldap
        ports:
        - containerPort: 389
          name: ldap
          protocol: TCP
        - containerPort: 636
          name: ldaps
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/ldap
          name: data
        - mountPath: /etc/ldap/slapd.d
          name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: openldap-pvc
      - emptyDir: {}
        name: config
status:
  conditions:
  - lastTransitionTime: "2026-07-30T00:02:02Z"
    lastUpdateTime: "2026-08-10T18:33:38Z"
    message: ReplicaSet "openldap-669f49d84c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2026-08-10T18:40:10Z"
    lastUpdateTime: "2026-08-10T18:40:10Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 8
