---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-unseal
  namespace: vault
  labels:
    app: vault-unseal

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-unseal-secret-reader
  namespace: vault
  labels:
    app: vault-unseal
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["vault-unseal-keys"]   # uniquement ce secret
    verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-unseal-secret-reader
  namespace: vault
  labels:
    app: vault-unseal
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vault-unseal-secret-reader
subjects:
  - kind: ServiceAccount
    name: vault-unseal
    namespace: vault
