---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: postgresql-clean-auth
  namespace: nova-syndicate
spec:
  encryptedData:
    password: AgCAF/trTXyD6SanaXABdbcj9M7i4Wi2lbWJRHUeWiPFaDAdZNP1a7rTmkjyhzYrjbCKOVRU5NjebzlivMUszsUr8b7GsLAWJrg9rvGqPUVYCdcRIdByZrEdUgTHAdhkrV6RG+VobRyo4NnZhILrmOiDQVWq2IZZhQ/ISEcl1dkLqsXeyhqos7ldEhfLU711O54LJYCinstiuzmEcly07sbheYw39YN3c8yrQmFQ0LJgl5W9kObyo28Ud6XInpPnJvnXjc1wRVT0GMnbKJTyzaOJ3axB//4/Zdwmtb3HHF+Luxjuy2OKBLmDmn8q81d1ba8mcYS2gO7N1Xbs4GLvUllXbcmJkp3zTVgesBzHxK+GOsDr/uxsEKx532wU0KKb0jsGfRC7gvk9++WmEytxXeO7+A9oJQQxCAZXsSlOP7fiixyMI+DQqOrfBiMvnJXpFeNLpE42Mdp6eCKH5oNgTRVYL9wluLxk0P3uNmHACW8xczWSBSj+lu7OdgwuZOC2IYgHt+bYPlitaNRDPqmFdBdfwNAjR6Vv1npMIzV6V08evccCAvGsvErsxwJxi3/yy3vtcrah+29WtTnYM0ne+TatGmqm5OpyDH2+zB54UKGhf4z7a/ZAV4Rk8CNYaOaRiXTxGmNbfQsSsWM0Vp8I/AAuTyfYpZOaeR/y0fT7CjpmmkPiU1zpaAaY3pXpCDCwNgAtnEYF45AP7E9q3+QpaAXaP73f0pE=
    postgres-password: AgBxNq76nk6HYIaNTzaViaZzg9kxLvjY1YIGXCzUbxbN99TrNMXXVA+jCHJYzNl87mIwvcBHoVUXwaNt0ZjZj3hYcRWNv8wlqPNGbQ/OjVhKiXBbVF6kJFaYiM61ghU9lf37Tx+DnQ7hQuTrVDyvd6VlAIqk3UgjP+YxgUg9MiwaCBPtCE1xCffIbHgO4i4L9WPCJ+C9F5lec+u3j5wfw3opZKK/jbhm+OyoaZPZq1W3BMzN9OVdbejrB976c5yAYAK4d30DUIYN3i35XmruZ+Fi2vHPHCEhLl/P1MJe+RESF5aI2PJmDCMtvBSt8PECfITXlbMQXhpSHzMfPCDvjSM7tE+NcCWvb2wbLYBlnR4beaMxU/uN20mOObjwqabQwoKcTeBYFS46oVOwEkxXL3vkjfxRuNQufKaDHv+G2EBqtYHoOFqXDx7wPli8u30bm0T8awiwcTwm3+Q4txPlT+SL17aFNZmmv2f/RqAcWHT/vSm5pzCdHVO9EMRB/Pykpjl4TDL8fL6q777L4bQwjNqoiIzXiWFrLv0Onw11Pg45HOBy2v3Nf3Nypr2DDIhFt4DbVAG3q7ReOd4fhamW5nw5/MhmR6VWQF7e4sBiPYO+92Plpn8l8c3ClhMoIOqga9o6jpqt7uLWnwuId0ZxEYCazBlS2iGuV1mWC0ICJN+gNZC/rObJCZGw0Et87Ats4fl/vmI8oSdqPrplQToQsiWfMppPdA4=
    replication-password: AgBLhhFWjBunkJrm3PnO5bqo+oxRd0Ve2gYLjsv6LqWlHiaGxUE46H9UN5UNL4+pIj7aAWRtFbsSD11wE1yoi32l7kaknwK1rELZ4DslS5XSNBBJ7RpmKWXtzachlLJh1nwXcMVfNPS3E5D6VYwImwo/eo8BDtfYxO/eIWheh9oRinF/V9wjpUZCdvPTZa1Nd4Fr03X3B6gCg3Qh5+5qEReqn+1Wr+J42CdS8xD1QGyGlmMe6lN3QH5d8dSQzhYOjjUshAr4J5xauBEEGo5jhiM1PNQNGhsQLO9J9ExF5SKiK5Vb5eM6Vytv316AGfLMtvmIRpVVyE7jr71UxkMF/QDLwaqxogHub+gAR+SNQaC882ttKbM/pNp7KQr/zuaqGVnhyfmhHL52AYrRYr0KZTe10c84cDuxUtqcbxjJrPQqLARXhKXlxDf+eXrNt5UL40Ld5jtCEp/eirMTedYGTwlNHYDIOr2GNmp9b3QpUYxPJbqgF319FT25eLchjeE8dONN0ZcWMIdvfuXSYddsBYcfhyDcDEgnJQCFAN28jKopctdhdYhAPJ7+7apc1pMofOlzBwN30+HL5TP3byIHWwPqf8o8FoUCN6PBKvqLGWvuRXEx35YIQ1HKBIyofcghfAOoMJs8SE+U4u7zr3/g0aM6PPLuwg0e+yeODZd9Sx7Qm7Dgk/g3VFSZMaTNOE7u3A0p1v0AKt3e+feJctZ1lDEm6Naf4kg=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: postgresql-clean-auth
      namespace: nova-syndicate
    type: Opaque
