apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
spec:
  template:
    spec:
      volumes:
        - name: website
          configMap:
            name: nginx-website
      containers:
        - name: nginx
          volumeMounts:
            - name: website
              mountPath: /usr/share/nginx/html
              readOnly: true
